---
- name: Descarga RPM.
  get_url:
    url: '{{ grafana }}'
    dest: /tmp
    mode: '0755'

- name: Instalar Grafana.
  package:
    name: '{{ grafana }}'
    state: present
    disable_gpg_check: true

- name: Iniciar servicio.
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Agregar permisos
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled

- name: Forzar cambios en el firewall.
  systemd:
    name: firewalld
    state: reloaded

- name: Chequear el puerto 3000
  wait_for:
    port: 3000
    state: started
    timeout: 10